version: 2
jobs:
  build:
    machine: True
    steps:
      - run:
          name: getting script
          command: wget https://raw.githubusercontent.com/revanthstrakz/script/master/circle_m31.bash
      - run:
          name: permissions for script
          command: chmod a+x circle_m31.bash
      - run:
          name: executing sxript
          command: ./circle_m31.bash

