version: 2
jobs:
  build:
    machine: True
    steps:
      - run:
          name: update
          command: sudo apt update
      - run:
          name: packages
          command: sudo apt install tar bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python
      - run:
          name: list
          command: ls
      - run:
          name: list
          command: df -h
      - run:
          name: nproc
          command: nproc
      - run:
          name: tools
          command: curl -O https://dl.google.com/android/repository/platform-tools-latest-linux.zip
      - run:
          name: mkdir
          command: mkdir -p ~/bin
      - run:
          name: mkdir
          command: mkdir -p ~/android/lineage
      - run:
          name: unzip platform tools
          command: curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      - run:
          name: unzip platform tools
          command: chmod a+x ~/bin/repo
      - run:
          name: mkdir
          command: git config --global user.email "dr.revanthstrakz@gmail.com"
      - run:
          name: mkdir
          command: git config --global user.name "Revanth Strakz"
      - run:
          name: mkdir
          command: PATH=~/platform-tools:$PATH
      - run:
          name: mkdir
          command: PATH=~/bin:$PATH
      - run:
          name: mkdir
          command: cd ~/android/lineage

